spring:
  profiles:
    active: salve1
  redis:
    database: 0
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}

rate:
  entry:
    max: 1000
    rate: 1000
  device:
    max: 10
    rate: 10

---
spring:
  profiles: slave1
netty:
  port: 8888

---
spring:
  profiles: slave2
netty:
  port: 9999